### ISSUE TITLE
1 column grid (simpleRow)

### ISSUE THREAD

**Issue by SventB** [laxap/bootstrap_grids#10]
You removed this grid but there is still TypoScript code and language labels for "simpleRow" in your extension.

But I beg you to enable the 1 column grid again, it's extremely useful for many tasks and in combination with other extensions.

**Comment by paulsen-it** [comment]
I need it too! Please bring back simpleRow

**Comment by laxap** [comment]
it's back in version 1.3.0

**Comment by SventB** [comment]
Hi @laxap,
in version 2.2.0 I'm missing it again, you removed it for TypoScript template "w/DataProcessing"?

**Comment by baggyownz** [comment]
hello,
I miss it too.
