### ISSUE TITLE
Copied content element retains in original grid

### ISSUE THREAD

**Issue by kludikovsky** [laxap/bootstrap_grids#23]
When copying a content element from a grid to another location the element shows up in the list view in the new location, but is rendered at the old (original) location.

_How to:_

- create two pages with a grid on each one
- place a content elemenet into the first pages grid
- copy the content element from the first page (in list view)
- goto to second page
- paste CE into this page
- CE shows up on this pages list view
-- but can not be found on page view
- output is placed on first page

I do understand that there must be somewhere a llink to the containing grid. which need to be aligned as well. But this can not be accessed.

Attached screenshost possibly makes it clearer.

![_screen_shot_2016-12-02_183300 d](https://cloud.githubusercontent.com/assets/6077916/20845044/4e0503ae-b8c3-11e6-9c9d-8aee14281e41.jpg)
![_screen_shot_2016-12-02_183009 d](https://cloud.githubusercontent.com/assets/6077916/20845052/5c21a3ca-b8c3-11e6-9ff1-cf2c8e949cfb.jpg)
![_screen_shot_2016-12-02_182956 d](https://cloud.githubusercontent.com/assets/6077916/20845053/603b79b8-b8c3-11e6-9013-85c7c8d9d0ea.jpg)

**Comment by laxap** [comment]
Copying grid elements with content elements in it and content elements from a grid elements all worked on my test instance. But I don't copy content elements in list view. I use the page view.

TYPO3 7.6.11, bootstrap_grids 1.3.1, gridelements 7.0.5.

**Comment by kludikovsky** [comment]
How can I do this over two pages?

**Comment by laxap** [comment]
![copy](https://cloud.githubusercontent.com/assets/10398927/21039956/094d8ff0-bde2-11e6-8f47-b95683d184c0.png)

![paste](https://cloud.githubusercontent.com/assets/10398927/21039963/13e2e2c6-bde2-11e6-8835-b4bd2c392394.png)

**Comment by laxap** [comment]
![pasteintogrid](https://cloud.githubusercontent.com/assets/10398927/21040086/db6c3554-bde2-11e6-9985-7a4f3b04f471.png)

**Comment by kludikovsky** [comment]
OK. Thanks.
Didn't know this.
