### ISSUE TITLE
missing grid-structure @ tabs from content

### ISSUE THREAD

**Issue by xerc** [laxap/bootstrap_grids#24]
Tabs from Content [[GRID-2],[GRID-2]] --> GRIDs are not rendered
<img width="676" alt="bildschirmfoto 2017-02-10 um 15 04 00" src="https://cloud.githubusercontent.com/assets/1372590/22829299/34aae8fe-efa2-11e6-8220-c926db90eb22.png">
<img width="1041" alt="bildschirmfoto 2017-02-10 um 15 02 23" src="https://cloud.githubusercontent.com/assets/1372590/22829268/0aef9ab4-efa2-11e6-89fe-37cfcac88b94.png">

**Comment by laxap** [comment]
You may change the typoscript configuration to support other grids in simple tabs. 

tt_content.gridelements_pi1.20.10.setup {
    tabsSimple.columns.101.renderObj.20 >
    tabsSimple.columns.101.renderObj.20 =< tt_content
}

If you change it you may have to set the header layout of some content elements to hidden. Otherwise the headers will be used as tab titles and shown in the tabs!

![typoscript-setup](https://cloud.githubusercontent.com/assets/10398927/24832087/48cbae30-1ca8-11e7-8937-94c11634e528.png)

![grids-tab-be](https://cloud.githubusercontent.com/assets/10398927/24832092/50175838-1ca8-11e7-803f-1bae07c93a64.png)

![grid-tab-fe](https://cloud.githubusercontent.com/assets/10398927/24832093/52d8e8e8-1ca8-11e7-9916-d5e0f8d1a5c9.png)

**Comment by xerc** [comment]
the problem occour if the content is in a SIMPLE-TAB on a sub-page and rendered via TS
```
  table = pages
  select.pidInList = this
  renderObj = COA
```
but caused by a wrong/missing {field:uid} the headers can not be fetched from database
@ https://github.com/laxap/bootstrap_grids/blob/master/Configuration/TypoScript/setup.txt
```
[70] where = tx_gridelements_container={field:uid}
```

**Comment by laxap** [comment]
Did you try switching from insertData to dataWrap?

Instead of:
```
where = tx_gridelements_container={field:uid}
where.insertData = 1
```
this:
```
where.dataWrap = tx_gridelements_container={field:uid}
```

Don't know if it works but dataWrap instead of insertData helped already in another case.

https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Text/Index.html

**Comment by xerc** [comment]
yes - tried both ways but without change
looks like the second query has wrong PID
> pid = 3
```
SELECT * FROM tt_content WHERE (tx_gridelements_container = 57 AND tt_content.deleted=0 AND tt_content.t3ver_state<=0 AND tt_content.pid<>-1 AND tt_content.hidden=0 AND (tt_content.fe_group='' OR tt_content.fe_group IS NULL OR tt_content.fe_group='0' OR FIND_IN_SET('0',tt_content.fe_group) OR FIND_IN_SET('-1',tt_content.fe_group)) AND colPos != -2 AND pid = 3 AND tx_gridelements_columns IN (101) AND sys_language_uid IN (-1,0) ) ORDER BY sorting ASC
```
> tt_content.pid IN (1)
```
SELECT header, uid, tx_gridelements_container, sorting, tt_content.pid as pid, tt_content.t3ver_state as t3ver_state FROM tt_content WHERE tt_content.pid IN (1) AND tx_gridelements_container=57 AND (tt_content.sys_language_uid =0) AND tt_content.deleted=0 AND tt_content.t3ver_state<=0 AND tt_content.pid<>-1 AND tt_content.hidden=0 AND (tt_content.fe_group='' OR tt_content.fe_group IS NULL OR tt_content.fe_group='0' OR FIND_IN_SET('0',tt_content.fe_group) OR FIND_IN_SET('-1',tt_content.fe_group)) ORDER BY sorting
```

**Comment by xerc** [comment]
search for data-field-uid="57" (it is hidden in the content)
