### ISSUE TITLE
[Suggestion] Add id-tag to outermost div to ease CSS

### ISSUE THREAD

**Issue by kludikovsky** [laxap/bootstrap_grids#27]
To be able to more easily format the elements especially th containing elements, it would be ggod to have the id-tag to the outmost div.
The setup.txt basically need to be changed to
          `dataWrap = <div id="c{field:uid}" class="row">|</div>`
on line 16, and some others as well.

Attach a modified file (not completely tested).
[setup.txt](https://github.com/laxap/bootstrap_grids/files/964830/setup.txt)

Maybe passing the layout and section_frame (needs decoding) would be advisable as well !?
        dataWrap = <div id="c{field:uid}" class="row frame-layout-{field:layout} my-section-frame{field:section_frame}">|</div>

**Comment by laxap** [comment]
I would not recommend to style/format elements based on the content element uid. If you delete/recreate an element or copy it to another page you would have to change/extend your stylesheet.

The column gridelements (2/3/4-cols) allow to add custom classes. You could extend the flexforms of the other gridelements to be able to add an additional custom class to other grids.

**Comment by kludikovsky** [comment]
Thi smight be good arguments, but if you need to style the outer element and have already used the class for something else, then your are stuck. Or if you only want to format one of the elements and not the whole class.
As this is a content-element it would be a good style as well to have this identified.

The only change to perform would be to add
   `id="c{field:uid}"`
in the datawrap in line 16 of `setup.txt`

And nobody is forced to use it.
