### ISSUE TITLE
Elements within bootstrap_grids not properly created and positioned

### ISSUE THREAD

**Issue by kludikovsky** [laxap/bootstrap_grids#28]
When I create a grid and then create an element within the grid by clicking the `+ Create new content element` the element will be created, but as soon as I save it, it seems to loose its 'context' and is stored as invalid column. (This might be a handling issue, but I can't find it.)

**Step-by-step**

- in the page view click  `+ Create new content element` in the required column
- fill in the header information (and evenually some text)
![_screen_shot_2017-05-08_165045b](https://cloud.githubusercontent.com/assets/6077916/25811428/90b0dea0-3413-11e7-9537-d119f4703ab1.jpg)

- save the CE
- after save the column is set to INVALID ...
![_screen_shot_2017-05-08_165056b](https://cloud.githubusercontent.com/assets/6077916/25811537/e4de8e50-3413-11e7-8132-05387b4d6789.jpg)
- CE is not associated to a proper column (colpos = -1 [ok], but no entries in the subcol

- the list view shows that the grid columns are not set for those created in the grid, while the one which has beend dragged is ok.
![_screen_shot_2017-05-08_172116b](https://cloud.githubusercontent.com/assets/6077916/25813204/eda3800e-3418-11e7-8fab-d85536c707d8.jpg)

This is the sequence of the templates
![image](https://cloud.githubusercontent.com/assets/6077916/25814140/a91723ce-341c-11e7-9655-403d15dfdacd.png)

`

bootstrap_grids 1.3.1
T3 7.6.18
php 7.0

**Comment by laxap** [comment]
I've tested in on a basic test instance and it worked.

In your "edit" screenshot the "Type" field seems to be empty too. That's strange.

- TYPO3 7.6.16
- gridelements 7.1.0
- bootstrap_grids 1.3.1
- PHP 7.0.15

![templates](https://cloud.githubusercontent.com/assets/10398927/26118124/02c7b454-3a69-11e7-866a-7df26f4b3a81.png)

![add-element](https://cloud.githubusercontent.com/assets/10398927/26118135/0b80a664-3a69-11e7-89b2-790411f1c983.png)

![create-element](https://cloud.githubusercontent.com/assets/10398927/26118141/110307c6-3a69-11e7-83bd-6fe75df7921b.png)

![edit-element](https://cloud.githubusercontent.com/assets/10398927/26118144/15bfa56c-3a69-11e7-8ed9-0c9cf8ebc751.png)

**Comment by maechler** [comment]
@kludikovsky That might be a common error when dealing with gridelements. You have to make sure that your custom element supports the columns `tx_gridelements_container` and `tx_gridelements_columns` otherwise they will not be set when the element is created in a grid column. Any element that wants to support being in gridelements has to have this configuration:

```
$GLOBALS['TCA']['tt_content']['types']['YOUR_CUSTOM_ELEMENT']['showitem'] = "
    //[..] whatever you need [..]
    --div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements, tx_gridelements_container, tx_gridelements_columns,
";
```

**Comment by kludikovsky** [comment]
@maechler Just help me to understand: What do you mean with 'custom element'?
I don't use anything 'custom' as self developed. I just have standard elements in use.
I would assume that such settings shall be done during installation for general usage, or am I wrong?

In the TCA I have grideelements just poping up in 3 places

![image](https://user-images.githubusercontent.com/6077916/28223325-4a8d8648-68cb-11e7-8765-cc21d85ccb11.png)

with the following entries:
`1
showitem = CType,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category,categories,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category,module_sys_dmail_category,--div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements,tx_gridelements_container,tx_gridelements_columns,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category, , --div--;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tabs.relation, tx_flux_parent, tx_flux_column, tx_flux_children;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tx_flux_children`

`gridelements_pi1
showitem = --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.general;general,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.header;header,tx_gridelements_backend_layout,pi_flexform,tx_gridelements_children,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames;frames,media,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.access,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.visibility;visibility,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category,categories,--div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements,tx_gridelements_container,tx_gridelements_columns,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category, , --div--;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tabs.relation, tx_flux_parent, tx_flux_column, tx_flux_children;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tx_flux_children`

`login
showitem = --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.general;general,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.header;header,rowDescription,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.plugin,pi_flexform,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.access,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.visibility;visibility,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames;frames,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.behaviour,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.extended,module_sys_dmail_category,--div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements,tx_gridelements_container,tx_gridelements_columns,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category,categories, , --div--;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tabs.relation, tx_flux_parent, tx_flux_column, tx_flux_children;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tx_flux_children`

**Comment by maechler** [comment]
@kludikovsky 
I am sorry I did not look very closely, but it is exactly the same error I had when I created a custom content element and forgot to add the columns `tx_gridelements_container` AND `tx_gridelements_columns`.

I do not know exactly why these columns are not present, but you have to make sure that your element also has that "Grid Elements" tab and the two fields you see here:

<img width="841" alt="screen shot 2017-07-15 at 15 14 14" src="https://user-images.githubusercontent.com/4113819/28239621-af9c0a8c-6970-11e7-90ef-89e106373fff.png">

When I compare your screenshots with them from @laxap, I see that he has these columns and you do not.
