### ISSUE TITLE
First-Item-Active issue if multiple Tab or Accordion elements occurring on one page

### ISSUE THREAD

**Issue by Moongazer** [laxap/bootstrap_grids#29]
If you place two or more "Tabs from content" or "Accordion from content" elements on one page, ONLY the very first item of the first Tab/Accordion element for that page becomes active. Especially for tabs it looks ugly if non of it is active.

I guess the problem is the the implementation of `register:TabCount` and `register:AccordionCount`, which seems to count all content-elements for a page instead of counting only the child content-elements inside the current Tab/Accordion. But as I said, this is just a guess because I couldn't really track down this issue.

Does anyone has an idea how to fix this?

TYPO3: 7.6.18
bootstrap_grids: 1.3.1

**Comment by maechler** [comment]
@Moongazer I had the same problem, the solution is to reset to tab counts:

```
# Reset tab counts
lib.bootstrap_grids.simpleTabs.append = COA
lib.bootstrap_grids.simpleTabs.append {
	5 = LOAD_REGISTER
	5 {
		TabCount2.cObject = TEXT
		TabCount2.cObject.data = register:TabCount2
		TabCount2.cObject.wrap = |*0
		TabCount2.prioriCalc = intval
	}
	10 = LOAD_REGISTER
	10 {
		TabCount.cObject = TEXT
		TabCount.cObject.data = register:TabCount
		TabCount.cObject.wrap = |*0
		TabCount.prioriCalc = intval
	}
}
```

The same solution should also solve the problem with the accordions.

**Comment by Moongazer** [comment]
Great, issue solved (I've tested only two SimpleTab elements on one page, but guess it working for the others too).
Thanks a lot :)

**Comment by maechler** [comment]
@Moongazer I have created a pull request for that, could you have a look at it?

https://github.com/laxap/bootstrap_grids/pull/30

**Comment by maechler** [comment]
@Moongazer I have also created a pull request, it contains also the settings for the accordion: https://github.com/laxap/bootstrap_grids/pull/30

You're welcome!

**Comment by jkbrands** [comment]
@maechler  Where do I have to place this code?

**Comment by macjohnny** [comment]
@jkbrands simply place it anywhere in your typoscript and make sure it overwrites the bootstrap_grids static template and not vice versa.
