### ISSUE TITLE
Compatibility with TYPO3 9.5 LTS

### ISSUE THREAD

**Issue by mvolland** [laxap/bootstrap_grids#39]
Is there a plan to make the extension and the 'bsdist' work for 9.5?

**Comment by romdum** [comment]
Hi,
I forked [the project](https://github.com/romdum/bootstrap_grids/) and change the composer.json file. Extension is already compatible with V9.

**Comment by wtfred** [comment]
@romdum Will you release on packagist, when gridelements will be release for 9.5 (not the dev-master)?
Thanks anyway :+1:

**Comment by anx-mwutte** [comment]
TYPO3 9.5 support: +1

**Comment by Outdoorsman** [comment]
Hi @romdum thanks for the link to your 9.5 compatible fork and for the **[pull request](https://github.com/laxap/bootstrap_grids/pull/40)** to `bootstrap_grids`... now here's hoping it gets merged so it can be official and we can all move on.

**Comment by wtfred** [comment]
@romdum if i'm not doing something wrong, looks like your fork isn't compatible with gridelements 9.0.0 / TYPO3 9.5.3 (i got nothing in frontend)
Maybe @Outdoorsman can confirm / infirm the behaviour?

**Comment by Moongazer** [comment]
Can confirm that current bootstrap_grids version 1.4 (for TYPO3 8) works out-of-the-box with gridelements 9.0 (for TYPO3 9) without any changes. Please adjust the version in `ext_emconf.php` and create an official release, thanks

**Comment by SventB** [comment]
This extension is compatible now
