### ISSUE TITLE
Gridelements not effective until titel of boostrap_grid element modified

### ISSUE THREAD

**Issue by kludikovsky** [laxap/bootstrap_grids#5]
_(This has already been accidently reported at https://forge.typo3.org/issues/72910)_

**Description**

The gridelements have no effect in the FE until the GE-title has been modified/edited/set.

**Steps**
in BE page view mode drag a new gridelement (2 column) from the top contentelement drop line
drag a text content element into the two columns
text contentelements are below each other
=> see Screenshot 1+2

edit title of gridelement
text elements are next to each other - as expected
=> see screenshots 3+4

[__Screenshots_.pdf](https://github.com/laxap/bootstrap_grids/files/103609/__Screenshots_.pdf)

**Comment by laxap** [comment]
Drag&drop supported since 1.2.0
