### ISSUE TITLE
 Compatibility with TYPO3 10.4 LTS

### ISSUE THREAD

**Issue by NeoBlack** [laxap/bootstrap_grids#50]
Is there a plan to make the extension work for 10.4?

**Comment by thethreeintheq** [comment]
Same question from me? Any plans for an update?

**Comment by baden32** [comment]
Dear Pascal, is there a plan to make the extension compatible with 10.x?

**Comment by 4auge** [comment]
I have made the experience that you only have to increase the version numbers of Typo3 and Gridelements in ext_emconf.php

So far I could not find any errors.
Are there similar experiences?

**Comment by thethreeintheq** [comment]
I've had the same experience. I ignored the warning in the installation process and so far it runs as usual under typo3 10.

**Comment by laxap** [comment]
https://github.com/laxap/bootstrap_grids/releases/tag/2.2.0
