### ISSUE TITLE
Compatible with Typo3 v11?

### ISSUE THREAD

**Issue by baden32** [laxap/bootstrap_grids#61]
Using version 2.0.0, I got a warning when I try to activate the extension in Typo3 11.5.6.
Could I just change the content of  ext_emconf.php to get ride of the warning or is bootstrap_grids version 2.0.0 not compatible withe latest Typo3 version?
Thank you in advance for your help.
Jo

**Comment by baggyownz** [comment]
hi there,
is there any new information about compatibility with TYPO3 11.x?
thanks

**Comment by RozbehSharahi** [comment]
Compatibility to TYPO3 v11 was just merged https://github.com/laxap/bootstrap_grids/pull/64.

However, I do not have rights to create a new tag. @laxap maybe you can create a new 3.0.0 tag.

until then dev-master installation should do the trick.

**Comment by RozbehSharahi** [comment]
A new version 3.0.0 was published and is now compatible with TYPO3 11. 

thx to @laxap

**Comment by outdoorsman** [comment]
Thank you soooooo much!
